from .common import MainMenuScene as MainMenuScene
from .common import NovelScene as NovelScene
from .decor import CreditScene as CreditScene
from .decor import HintScene as HintScene
from .decor import SplashScene as SplashScene
from .level import MagicGestureScene as MagicGestureScene
from .level import MlrsScene as MlrsScene
from .level import PacmanScene as PacmanScene
from .level import RpsScene as RpsScene
